# Generated by Django 3.2.6 on 2022-01-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
